### ISSUE TITLE
It doesn't work when configured by provisioning

### ISSUE THREAD

**Issue by davidrios** [grafana/grafana-amazonprometheus-datasource#377]
**What happened**:
I'm trying to configure this datasource by provisioning, but it can't authenticate and just gives 403 errors.
If I set editable: true in the provisioning, then go to the datasource page and click save & test then it works.
Basically I can't leave it as non editable because for some reason it won't connect unless I'm able to save & test at least once from the UI.

**What you expected to happen**:
Connection works and Prometheus is queryable even if provision is not editable

**How to reproduce it (as minimally and precisely as possible)**:

Use a provisioning config like this:
```yaml
- name: Amazon Prometheus
        type: grafana-amazonprometheus-datasource
        url: https://aps-workspaces.eu-west-1.amazonaws.com/workspaces/ws-xxx
        isDefault: true
        jsonData:
          sigV4Region: eu-west-1
```

Restart Grafana and try to query, or even go to the datasource page and click the `Test` button, it will give 403.

If adding editable:

```yaml
- name: Amazon Prometheus
        type: grafana-amazonprometheus-datasource
        url: https://aps-workspaces.eu-west-1.amazonaws.com/workspaces/ws-xxx
        isDefault: true
        editable: true
        jsonData:
          sigV4Region: eu-west-1
```
then going to the datasource page and clicking `Save & test` at least once, then it works.

**Environment**:

- Grafana version: 12
- Plugin version: 2.1.0
- OS Grafana is installed on: k8s using the helm chart
